### ISSUE TITLE
Ceph and Vault

### ISSUE THREAD

**Issue by zunder1990** [kerberos-io/vault#13]
I testing out kerberos and trying to get vault connected to my ceph cluster. I see you list it as supported but looks like just needs the docs made up. https://doc.kerberos.io/vault/providers/#ceph  
When I try to set it up in vault dont see it in the drop down
![image](https://github.com/kerberos-io/vault/assets/11825392/5286eac1-9c79-4406-b567-d6d21ac53e6e)

am I missing something?

**Comment by cedricve** [comment]
@zunder1990  Correct, docs still need to be defined for Ceph. However we apply Ceph through the S3 layer, once you have that setup/configured. You can select the `Minio` provider, and configure the S3 credentials

**Comment by zunder1990** [comment]
ok thanks
