### ISSUE TITLE
STORAGE_API_URL ignored

### ISSUE THREAD

**Issue by vosdev** [kerberos-io/vault#8]
Hello,

I deployed the Vault as described in the instructions. I am unable to login.

in the browser console I can see it is trying to post to `api.mydomain.com/login`. 

This does not match the environment value I set for `STORAGE_API_URL`, which is `kerberos-api.mydomain.com`

I can exec into the vault pod and `env | grep STORAGE_API_URL` to confirm that the environment variable is set.

![image](https://user-images.githubusercontent.com/45820840/220466960-4a97d56d-7b0f-4157-9b5a-c30afea83ddc.png)

**Comment by JoeTular** [comment]
Has there been any resolution to this issue? I am having the same issue

**Comment by cedricve** [comment]
I might have missed this apologies! Can you share the Kerberos Vault `yaml` file you have applied?

**Comment by cedricve** [comment]
we have simplified this in latest release. Now both the API and Frontend are merged into a single binary (port). You can now simply use a `LoadBalancer` or single `Ingress`. Hope this will help a lot of people trying to set things up! https://github.com/kerberos-io/vault/releases/tag/1.0.817949156

**Comment by vosdev** [comment]
Sorry for the late response. Personal life caught up. I'll give it another shot at setting up when I have the time and will let you know how things go!
